USE [cpx]
GO

/****** Object:  Table [dbo].[Region_HLI_CLEAN]    Script Date: 2/23/2017 6:37:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Region_HLI_CLEAN](
	[Version] [smallint] NULL,
	[Shipment Date] [datetime] NULL,
	[Profit Center L0 Name] [varchar](20) NULL,
	[Profit Center L1 Name] [varchar](20) NULL,
	[Profit Center L2 Name] [varchar](50) NULL,
	[Sales Order ID] [varchar](20) NULL,
	[Sales Order Line Item ID] [varchar](20) NULL,
	[Sales Order Source System Key] [varchar](20) NULL,
	[Sales Product Type Descr] [varchar](20) NULL,
	[Legacy Sales Order ID] [varchar](20) NULL,
	[Legacy Sales Order Line Item ID] [varchar](20) NULL,
	[GA AMID 4 NAME] [varchar](200) NULL,
	[GA AMID 2 ID] [varchar](20) NULL,
	[GA AMID 2 NAME] [varchar](200) NULL,
	[Sales Order Type Category Code] [varchar](20) NULL,
	[SNP Group Source Code] [varchar](20) NULL,
	[Global Business Unit Name] [varchar](20) NULL,
	[Higher Level Item Flag] [varchar](1) NULL,
	[OSS Higher Level Item] [varchar](20) NULL,
	[OSS Status On Item] [varchar](50) NULL,
	[Fulfillment OSS Status On Item] [varchar](20) NULL,
	[Parent Sales Order Item ID] [varchar](20) NULL,
	[Plant Code] [varchar](10) NULL,
	[Product Descr] [varchar](255) NULL,
	[Product Family Descr] [varchar](255) NULL,
	[Product ID] [varchar](20) NULL,
	[Product Line ID] [varchar](20) NULL,
	[Route Code] [varchar](10) NULL,
	[Sales Order Header Complete Delivery Flag] [varchar](10) NULL,
	[Base Quantity] [real] NULL,
	[Secured Position Net USD Amount] [real] NULL,
	[Ship To ISO Country Name] [varchar](40) NULL,
	[Shipment ID] [varchar](20) NULL,
	[OSS Shipment No] [varchar](20) NULL,
	[OSS SAP DeliveryNo] [varchar](20) NULL,
	[Shipment Line Item ID] [varchar](20) NULL,
	[Shipment to ISO Country Code] [varchar](10) NULL,
	[Shipping Receiving Point Code] [varchar](20) NULL,
	[Sold To Customer Name] [varchar](100) NULL,
	[Supplier] [varchar](50) NULL,
	[Supplying Division Sub Entity Code] [varchar](10) NULL,
	[Team] [varchar](20) NULL,
	[Focus Account Group] [varchar](50) NULL,
	[Unit Quantity] [real] NULL,
	[HPS Segment] [varchar](50) NULL,
	[ISS vs BCS Split] [varchar](10) NULL,
	[ASAP Flag] [varchar](1) NULL,
	[Business Area Code] [varchar](20) NULL,
	[Complexity Groups] [varchar](20) NULL,
	[Solution Order (Y N)] [varchar](1) NULL,
	[Coordination of Delivery Code] [varchar](20) NULL,
	[Delivery Priority Code] [varchar](20) NULL,
	[Delivery Priority Group] [varchar](100) NULL,
	[Derived End Customer Name] [varchar](200) NULL,
	[Distribution Center Code] [varchar](20) NULL,
	[B2B Sales Order ID] [varchar](20) NULL,
	[B2B Sales Order Line Item ID] [varchar](20) NULL,
	[B2B Concatenated Sales Order User Status Code] [varchar](200) NULL,
	[B2B Concatenated Sales Order Line Item User Status Code] [varchar](200) NULL,
	[Concatenated Sales Order User Status Code] [varchar](200) NULL,
	[Concatenated Sales Order Line Item User Status Code] [varchar](200) NULL,
	[B2B Shipment Date] [datetime] NULL,
	[B2B Shipment ID] [varchar](20) NULL,
	[B2B Shipment Line Item Identifier] [varchar](20) NULL,
	[Estimated End To End Transit Day No] [smallint] NULL,
	[Clean Order Date] [datetime] NULL,
	[Fulflmt Clean Order Date] [datetime] NULL,
	[Fulflmt ASAP Flag] [varchar](1) NULL,
	[Fulflmt Delivery Priority Code] [varchar](20) NULL,
	[Fulflmt Higher Level Item Flag] [varchar](1) NULL,
	[Fulflmt Plant Code] [varchar](20) NULL,
	[Fulflmt Route Code] [varchar](20) NULL,
	[Fulflmt Sales Order Header Distribution Center Code] [varchar](20) NULL,
	[Fulflmt Sales Order Header Complete Delivery Flag] [varchar](1) NULL,
	[Fulflmt Coordination of Delivery Code] [varchar](20) NULL,
	[Fulflmt Shipment Date] [datetime] NULL,
	[Fulflmt Shipping Receiving Point Code] [varchar](20) NULL,
	[B2B Sales Order Header Source System Key] [varchar](20) NULL,
	[GA AMID 4 ID] [varchar](20) NULL,
	[Supplier Complexity Group] [varchar](20) NULL,
	[Sales Document Item Category Code] [varchar](10) NULL,
	[Fulflmt Sales Document Item Category Code] [varchar](10) NULL,
	[Sales Organization Code] [varchar](10) NULL,
	[Special Process] [varchar](100) NULL,
	[HP Receive Date] [datetime] NULL,
	[Sales Order Detail Create Timestamp] [datetime] NULL,
	[Sales Order Detail Create Timestamp Local] [datetime] NULL,
	[Fulflmt Sales Order Detail Create Date] [datetime] NULL,
	[Create] [datetime] NULL,
	[Clean Item Date Time] [datetime] NULL,
	[Clean Item Date Time Local] [datetime] NULL,
	[Fulflmt Clean Item Date Time] [datetime] NULL,
	[Fulflmt Clean Item Date Time Local] [datetime] NULL,
	[Clean Header Date Time] [datetime] NULL,
	[Clean Header Date Time Local] [datetime] NULL,
	[Fulflmt Clean Header Date Time] [datetime] NULL,
	[Fulflmt Clean Header Date Time Local] [datetime] NULL,
	[Clean] [datetime] NULL,
	[Production Start Date] [datetime] NULL,
	[Production Start Date Local] [datetime] NULL,
	[Drop to Factory Timestamp] [datetime] NULL,
	[Drop to Factory Timestamp Local] [datetime] NULL,
	[Fulflmt Drop to Factory Timestamp] [datetime] NULL,
	[Fulflmt Drop to Factory Timestamp Local] [datetime] NULL,
	[Fulflmt Production Start Date] [datetime] NULL,
	[Fulflmt Production Start Date Local] [datetime] NULL,
	[Production Start] [datetime] NULL,
	[Factory Ship Date Time] [datetime] NULL,
	[Factory Ship Date Time Local] [datetime] NULL,
	[Fulflmt Factory Ship Date Time] [datetime] NULL,
	[Fulflmt Factory Ship Date Time Local] [datetime] NULL,
	[Factory Ship] [datetime] NULL,
	[OSS Cust Ship Date] [datetime] NULL,
	[OSS Cust Ship Date Local] [datetime] NULL,
	[Fulflmt OSS Cust Ship Date] [datetime] NULL,
	[Fulflmt OSS Cust Ship Date Local] [datetime] NULL,
	[Customer Ship] [datetime] NULL,
	[Special Type of Order] [varchar](100) NULL,
	[Hub Receive Date] [datetime] NULL,
	[Hub Receive Date Local] [datetime] NULL,
	[Fulflmt Hub Receive Date] [datetime] NULL,
	[Fulflmt Hub Receive Date Local] [datetime] NULL,
	[Hub Receive] [datetime] NULL,
	[OSS POD Date] [datetime] NULL,
	[Fulflmt OSS POD Date] [datetime] NULL,
	[Delivery] [datetime] NULL,
	[Customer Requested Delivery Date] [datetime] NULL,
	[Fulflmt Requested Delivery Date] [datetime] NULL,
	[Actual Customer Requested Delivery Date] [datetime] NULL,
	[First Planned Fact Ship Date] [datetime] NULL,
	[Fulflmt First Planned Fact Ship Date] [datetime] NULL,
	[First Planned Cust Ship] [datetime] NULL,
	[Fulflmt First Planned Cust Ship] [datetime] NULL,
	[First Planned Delivery Date] [datetime] NULL,
	[Fulflmt First Planned Delivery Date] [datetime] NULL,
	[Planned Factory Ship Date] [datetime] NULL,
	[Fulflmt Planned Factory Ship Date] [datetime] NULL,
	[First Touchpoint Scheduled Ship Timestamp] [datetime] NULL,
	[Last Touchpoint Scheduled Ship Timestamp] [datetime] NULL,
	[Planned Cust Ship Date] [datetime] NULL,
	[Planned Delivery Date] [datetime] NULL,
	[Production Done Date] [datetime] NULL,
	[Production Done Date Local] [datetime] NULL,
	[Fulflmt Production Done Date] [datetime] NULL,
	[Fulflmt Production Done Date Local] [datetime] NULL,
	[Production Done] [datetime] NULL,
	[Release2Fulfillment Date] [datetime] NULL,
	[Release2Fulfillment Date Local] [datetime] NULL,
	[Fulflmt Release2Fulfillment Date] [datetime] NULL,
	[Fulflmt Release2Fulfillment Date Local] [datetime] NULL,
	[SCOUT Delivered Date Time] [datetime] NULL,
	[Fulflmt SCOUT Delivered Date Time] [datetime] NULL,
	[SCOUT Latest Carrier Status Code] [varchar](10) NULL,
	[Fulflmt SCOUT Latest Carrier Status Code] [varchar](10) NULL,
	[SCOUT Latest Carrier Status Desc] [varchar](255) NULL,
	[Fulflmt SCOUT Latest Carrier Status Desc] [varchar](255) NULL,
	[SCOUT Latest Carr Status Reason Code] [varchar](20) NULL,
	[Fulflmt SCOUT Latest Carr Status Reason Code] [varchar](20) NULL,
	[SCOUT Latest Carr Status Reason Desc] [varchar](255) NULL,
	[Fulflmt SCOUT Latest Carr Status Reason Desc] [varchar](255) NULL,
	[SCOUT Pod Submission Date] [datetime] NULL,
	[Fulflmt SCOUT Pod Submission Date] [datetime] NULL,
	[DTFC -3 0] [numeric](18, 0) NULL,
	[DTFC -x 0] [numeric](18, 0) NULL,
	[DTCRD 0 0] [numeric](18, 0) NULL,
	[DTCRD -x 0] [numeric](18, 0) NULL,
	[DTACRD -x 0] [numeric](18, 0) NULL,
	[STFC -x 0] [numeric](18, 0) NULL,
	[STFC -2 0] [numeric](18, 0) NULL,
	[STFC -3 0] [numeric](18, 0) NULL,
	[STFA -x 0] [numeric](18, 0) NULL,
	[STFA -2 0] [numeric](18, 0) NULL,
	[STFA -3 0] [numeric](18, 0) NULL,
	[RE to CR] [numeric](18, 0) NULL,
	[RE to CL] [numeric](18, 0) NULL,
	[RE to FS] [numeric](18, 0) NULL,
	[Re to CS] [numeric](18, 0) NULL,
	[RE to Del] [numeric](18, 0) NULL,
	[CL to BT] [numeric](18, 0) NULL,
	[CL to FS] [numeric](18, 0) NULL,
	[BT to FGI] [numeric](18, 0) NULL,
	[FGI to FS] [numeric](18, 0) NULL,
	[FS to CS] [numeric](18, 0) NULL,
	[BT to FS] [numeric](18, 0) NULL,
	[FS to Hub R] [numeric](18, 0) NULL,
	[Hub R to Hub S] [numeric](18, 0) NULL,
	[CS to Del] [numeric](18, 0) NULL,
	[CR to CL] [numeric](18, 0) NULL,
	[Order_RE-CR] [varchar](50) NULL,
	[Order_CR-CL] [varchar](50) NULL,
	[Order_RE-CL] [varchar](50) NULL,
	[DG_RE-CR] [varchar](50) NULL,
	[DG_RE-CL] [varchar](50) NULL,
	[DG_RE-FS] [varchar](50) NULL,
	[DG_RE-CS] [varchar](50) NULL,
	[DG_RE-DE] [varchar](50) NULL,
	[DG_CR-CL] [varchar](50) NULL,
	[DG_CL-BT] [varchar](50) NULL,
	[DG_CL-FGI] [varchar](50) NULL,
	[DG_CL-FS] [varchar](50) NULL,
	[DG_BT-FGI] [varchar](50) NULL,
	[DG_BT-FS] [varchar](50) NULL,
	[DG_BT-CS] [varchar](50) NULL,
	[DG_FGI-FS] [varchar](50) NULL,
	[DG_FS-HR] [varchar](50) NULL,
	[DG_FS-CS] [varchar](50) NULL,
	[DG_HR-CS] [varchar](50) NULL,
	[DG_CS-DE] [varchar](50) NULL,
	[DG_FAck-FS] [varchar](50) NULL,
	[DG_LAck-FS] [varchar](50) NULL,
	[DG_FCS-CS] [varchar](50) NULL,
	[DG_LCS-CS] [varchar](50) NULL,
	[DG_FCD-DE] [varchar](50) NULL,
	[DG_LCD-DE] [varchar](50) NULL,
	[DG_CRD-DE] [varchar](50) NULL,
	[DG_ACRD-DE] [varchar](50) NULL,
	[MultiShipFlag] [varchar](1) NULL,
	[HLI_ID] [varchar](20) NULL,
	[ITM_COUNT] [smallint] NULL,
	[ConfigText] [varchar](3000) NULL,
	[Ctry_Rgn] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


